version: '3.8'
services:

  postgres-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mvp_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  mvp_data:
