require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/supplier_contacts", type: :request do
  let(:supplier) { FactoryBot.create(:supplier) }
  before do
    login_user
  end
  # This should return the minimal set of attributes required to create a valid
  # SupplierContact. As you add validations to SupplierContact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SupplierContact.create! valid_attributes
      get supplier_supplier_contacts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      supplier_contact = SupplierContact.create! valid_attributes
      get supplier_supplier_contact_url(supplier_contact)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_supplier_supplier_contact_path(supplier_id: supplier.id)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      supplier_contact = SupplierContact.create! valid_attributes
      get edit_supplier_supplier_contact_url(supplier_contact)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SupplierContact" do
        expect {
          post supplier_supplier_contacts_url(supplier_id: supplier.id), params: { supplier_contact: valid_attributes }
        }.to change(SupplierContact, :count).by(1)
      end

      it "redirects to the created supplier_contact" do
        post supplier_supplier_contacts_url(supplier_id: supplier.id), params: { supplier_contact: valid_attributes }
        expect(response).to redirect_to(supplier_supplier_contact_url(SupplierContact.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SupplierContact" do
        expect {
          post supplier_supplier_contacts_url(supplier_id: supplier.id), params: { supplier_contact: invalid_attributes }
        }.to change(SupplierContact, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post supplier_supplier_contacts_url(supplier_id: supplier.id), params: { supplier_contact: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supplier_contact" do
        supplier_contact = SupplierContact.create! valid_attributes
        patch supplier_supplier_contact_url(supplier_contact), params: { supplier_contact: new_attributes }
        supplier_contact.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the supplier_contact" do
        supplier_contact = SupplierContact.create! valid_attributes
        patch supplier_supplier_contact_url(supplier_contact), params: { supplier_contact: new_attributes }
        supplier_contact.reload
        expect(response).to redirect_to(supplier_supplier_contact_url(supplier_contact))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        supplier_contact = SupplierContact.create! valid_attributes
        patch supplier_supplier_contact_url(supplier_contact), params: { supplier_contact: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested supplier_contact" do
      supplier_contact = SupplierContact.create! valid_attributes
      expect {
        delete supplier_supplier_contact_url(supplier_contact)
      }.to change(SupplierContact, :count).by(-1)
    end

    it "redirects to the supplier_contacts list" do
      supplier_contact = SupplierContact.create! valid_attributes
      delete supplier_supplier_contact_url(supplier_contact)
      expect(response).to redirect_to(supplier_supplier_contacts_url)
    end
  end
end
